# Generated by Django 6.0.1 on 2026-02-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommendations', '0003_alter_category_options_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
